# frozen_string_literal: true

require_relative "../lib/rsyntaxtree"
require_relative "example_options"

# Builds the text handed to a language model that has to write this notation:
# the reference, the manual and every gallery example, from the files those
# already live in. Nothing here is authored — a second copy of the notation
# would drift from the one the parser reads.
module LlmPayload
  module_function

  ROOT = File.expand_path(File.join(__dir__, ".."))
  SITE = "https://yohasebe.github.io/rsyntaxtree"

  def version
    File.read(File.join(ROOT, "lib", "rsyntaxtree", "version.rb"))[/VERSION\s*=\s*"([^"]+)"/, 1]
  end

  def notation_core
    File.read(File.join(ROOT, "lib", "rsyntaxtree", "notation_core.md")).rstrip
  end

  # The manual as the site publishes it, minus the front matter, with the
  # tables Jekyll pulls in resolved. Those two tables carry the box, circle
  # and escape notation, so leaving the include tags unresolved would drop
  # exactly the part a model needs.
  def manual
    md = File.read(File.join(ROOT, "docs", "documentation.md"))
    # The contents are generated by the site; in the file they are the stub
    # that `{:toc}` marks. Drop that, then start at the first section: what
    # is left above it is the page title and the switch to the Japanese
    # edition, neither of which belongs in a file that is the content.
    md = md.sub(/^###[^\n]*\n\{:[^}]*\}\n\n1\.\s*toc\n\{:toc\}\n/, "")
    md = md[/^###\s.*/m].to_s
    md = md.gsub(/\{%-?\s*include\s+(\S+?)\s*-?%\}/) do
      table_to_list(File.join(ROOT, "docs", "_includes", Regexp.last_match(1)))
    end
    # Kramdown attributes address the rendered page and mean nothing here.
    md.gsub(/^\{:[^}]*\}\n/, "").strip
  end

  # An HTML table from _includes as a list. Not as a table: half of what these
  # tables hold is notation containing `|` — `||`, `|/|`, `|1|` — which is the
  # column separator, so the rows come out ambiguous. The output column of the
  # box-and-circle table is a picture; its file name says what is drawn, so
  # that name stands in for the image.
  def table_to_list(path)
    rows = File.read(path).scan(%r{<tr[^>]*>(.*?)</tr>}m).flatten.map do |row|
      row.scan(%r{<t[dh][^>]*>(.*?)</t[dh]>}m).flatten.map { |cell| cell_to_text(cell) }
    end
    rows.reject! { |r| r.empty? || r.all?(&:empty?) }
    return "" if rows.empty?

    rows.shift # the header says input and output, which the arrow already says
    rows.map { |r| "- `#{r.first}` → #{r.drop(1).reject(&:empty?).join(' — ')}" }.join("\n")
  end

  # Tags are removed by name rather than by pattern: a cell may hold a bare
  # `<` (the escape table has `\<` in it), which a general tag pattern eats.
  # Entities are decoded afterwards for the same reason.
  def cell_to_text(cell)
    text = cell.gsub(%r{<img[^>]*src='[^']*/([^/']+)\.png'[^>]*/?>}) { Regexp.last_match(1).tr("_", " ") }
    text = text.gsub(%r{<img[^>]*>}, "")
    ["<code>", "</code>", "<b>", "</b>", "<br />", "<br/>", "<br>"].each { |t| text = text.gsub(t, "") }
    text = text.gsub("&lt;", "<").gsub("&gt;", ">").gsub("&amp;", "&").gsub("&nbsp;", " ")
    text.gsub(/\s+/, " ").strip
  end

  # Every gallery example, with the options the gallery records for it. The
  # names are the ones the library takes, not the ones the front matter uses,
  # and a value equal to the default is left out.
  #
  # Left out by value, not by effect: `fontstyle=noto-sans` resolves to the
  # default `sans` and so changes nothing, but it is a different string and is
  # listed. Resolving it here would mean a second copy of the alias rules that
  # lib/rsyntaxtree.rb applies, which is the thing this file exists to avoid.
  # A setting that changes nothing is harmless to pass on; a rule written twice
  # is not.
  def examples
    dir = File.join(ROOT, "docs", "_examples")
    Dir.glob("*.md", base: dir).sort.filter_map do |md|
      path = File.join(dir, md)
      front = YAML.load_file(path)
      name, opts = ExampleOptions.load(path)
      category = front["category"].to_s
      next if category == "Test" || category == "Error"

      { name: name,
        caption: front["caption"].to_s,
        category: category,
        reference: front["reference"].to_s,
        settings: settings_for(opts),
        notation: opts[:data].strip }
    end
  end

  def settings_for(opts)
    opts.reject { |k, v| %i[data name format].include?(k) || DEFAULT_OPTS[k].to_s == v.to_s }
        .sort_by { |k, _| k.to_s }
        .map { |k, v| "#{k}=#{v}" }
        .join(" ")
  end

  # --- the three files ---

  def examples_document
    ex = examples
    out = +<<~HEAD
      RSyntaxTree examples: #{ex.size} trees, every one verified to draw.

      Each is the input behind a figure in the gallery at #{SITE}/examples.
      The settings line names the options the gallery records for that figure;
      anything not named is at its default. The test suite runs every input
      here through the same parser that draws it, so each one is accepted.

      Notation reference: rsyntaxtree --notation
      Check an input without drawing: rsyntaxtree --validate "[S [NP a] [VP b]]"

      What the option names on a settings line mean is not in this file, nor in
      the reference, which leaves the options out on purpose. For those, see
      `rsyntaxtree --help` or the manual: #{SITE}/documentation. Everything at
      once, this file and the manual together: #{SITE}/llms-full.txt
    HEAD
    ex.each do |e|
      out << "\n\n## #{e[:name]} — #{e[:caption]}\n\n"
      out << "Category: #{e[:category]}\n"
      out << "Settings: #{e[:settings].empty? ? '(all default)' : e[:settings]}\n"
      out << "Source: #{e[:reference]}\n" unless e[:reference].empty?
      out << "\n```\n#{e[:notation]}\n```"
    end
    out << "\n"
  end

  def index_document
    <<~TXT
      # RSyntaxTree

      > A generator for linguistic syntax trees. The input is labeled bracket
      > notation; the output is PNG, SVG, PDF, TikZ or LSIF. Version #{version}.

      The notation is small, and several characters in it already mean
      something. The brief leads with those traps, which is why it is worth
      reading before writing any, and why what you write is worth checking
      rather than guessing.

      ## Start here

      - [llms-full.txt](#{SITE}/llms-full.txt): one file, and the only one needed.
        It opens with the rules and the four traps in about fifty lines, then
        the manual, then all #{examples.size} examples with the options each was drawn with.

      ## The same material as pages

      - [Manual](#{SITE}/documentation): every construction, with figures
      - [Gallery](#{SITE}/examples): #{examples.size} trees across linguistic frameworks, each verified to draw

      ## Checking your work

      `rsyntaxtree --validate "[S [NP the cat] [VP sat]]"` answers with JSON and
      an exit code, drawing nothing. A refusal names the cause, the label it is
      in, and a one-line fix that was confirmed by applying it and parsing again.
    TXT
  end

  def full_document
    <<~HEAD + "\n#{notation_core}\n\n\n# Manual\n\n#{manual}\n\n\n# Examples\n\n#{examples_document}"
      # RSyntaxTree #{version} — notation, manual and examples

      Everything a language model needs in order to write this notation, in one
      file: the brief that leads with the traps, the manual as the site
      publishes it, and every gallery example with the options it needs.

      Generated from the sources the tool itself reads. Check what you write
      with `rsyntaxtree --validate`, which draws nothing and reports the cause
      of a refusal along with a fix known to work.

      # Notation, in brief
    HEAD
  end
end
