# frozen_string_literal: true

# Records the pixel size of every gallery figure in docs/_data/figure_sizes.yml.
#
# The gallery used to hand each PNG to the browser with no size, so a figure
# was drawn at its natural size when it fitted the column and shrunk when it
# did not. Since a tree's pixel size follows its content, that meant a short
# tree appeared at 100% next to a wide one at 30%, and the same 16px label
# looked twice as large in one figure as in the next. The template scales every
# figure by the same factor instead, which it can only do if it knows how big
# each one is — Jekyll cannot read image dimensions on GitHub Pages.
#
# Run from the repository root, after generating the examples:
#   ruby dev/stamp_figure_sizes.rb

require "yaml"
require "fileutils"

IMG_DIR = File.expand_path("../docs/assets/img", __dir__)
DATA_FILE = File.expand_path("../docs/_data/figure_sizes.yml", __dir__)

# Width and height out of the PNG's IHDR chunk, which always starts at byte 16.
def png_size(path)
  header = File.binread(path, 24)
  raise "#{path}: not a PNG" unless header && header[1, 3] == "PNG"

  header[16, 8].unpack("N2")
end

sizes = Dir.glob(File.join(IMG_DIR, "*.png")).sort.each_with_object({}) do |path, acc|
  name = File.basename(path, ".png")
  width, height = png_size(path)
  acc[name] = { "width" => width, "height" => height }
end

abort "no figures found in #{IMG_DIR}" if sizes.empty?

FileUtils.mkdir_p(File.dirname(DATA_FILE))

File.write(DATA_FILE, <<~HEADER + sizes.to_yaml.sub(/\A---\n/, ""))
  # Generated by dev/stamp_figure_sizes.rb — do not edit by hand.
  # Pixel size of each gallery figure, so the examples page can scale them all
  # by one factor instead of letting small trees display at full size.
HEADER

puts "wrote #{sizes.size} figure sizes to #{DATA_FILE.sub(Dir.pwd + "/", "")}"
