# frozen_string_literal: true

# Records the display size of every gallery figure in docs/_data/figure_sizes.yml.
#
# The gallery used to hand each PNG to the browser with no size, so a figure was
# drawn at its natural size when it fitted the column and shrunk when it did
# not. Since a tree's pixel size follows its content, a short tree appeared at
# 100% next to a wide one at 30%, and the same 16px label looked twice as large
# in one figure as in the next.
#
# A single scale factor for every figure is no better: it either leaves the
# small figures too large or shrinks them past the point of being readable.
# So the factor varies with the figure's own width:
#
#   displayed width = k * width ** EXPONENT
#
# An exponent below 1 makes the displayed width grow more slowly than the
# figure itself, which is exactly the compression the eye is asking for; k is
# set so that a 280px figure lands at about 90%. The result runs roughly 100%
# for a tiny tree, 90% at 280px, 77% at 520px and 65% at 690px — a gradient
# rather than the step a fixed factor produces. Nothing is ever scaled up, and
# a figure too tall or too wide for the page is brought back below.
#
# Jekyll cannot measure images on GitHub Pages, hence this file. Run from the
# repository root, after generating the examples:
#
#   ruby dev/stamp_figure_sizes.rb

require "yaml"
require "fileutils"

IMG_DIR = File.expand_path("../docs/assets/img", __dir__)
DATA_FILE = File.expand_path("../docs/_data/figure_sizes.yml", __dir__)
DOC_DIR = File.expand_path("../docs/assets/doc", __dir__)
DOC_DATA_FILE = File.expand_path("../docs/_data/doc_figure_sizes.yml", __dir__)

# A manual figure stands beside its code. How much of the row it gets depends
# on how wide it is: one narrow enough keeps the even split, a wider one takes
# two thirds, and one wider still goes under the code with the row to itself.
# Without the tiers a wide figure is squeezed into half a row and its lettering
# comes out half the size of the lettering in the figure above it.
DOC_LAYOUTS = [
  { max_width: 460.0, css_class: "",           column: 460.0 },
  { max_width: 610.0, css_class: "grid-wide",  column: 610.0 },
  { max_width: nil,   css_class: "grid-stack", column: 940.0 }
].freeze

# How much of the row a figure gets, as a class on the grid in
# docs/assets/css/style.scss: a figure narrow enough to sit beside the bracket
# notation keeps the even split, a wider one takes two thirds of the row, and
# one wider still gets a row of its own below the notation.
#
# The tier is chosen by the width the easing asks for, not by the figure's own
# width. Picking by the latter meant the column then clipped what the easing had
# asked for, and the scale stopped being monotonic across a boundary: a 1366px
# figure was shown at 44% while one 6% wider, in the next tier, got 60%. Chosen
# this way the requested width never exceeds the row it lands in, so every
# figure sits on the easing curve and the scale falls smoothly with size.
#
# The height limit is looser in the last tier: a stacked figure has the full
# width of the page and no notation beside it, and vertical space is what a
# scrolling page has most of.
LAYOUTS = [
  { max_eased: 448.0, css_class: "",           max_height: 900.0 },
  { max_eased: 604.0, css_class: "grid-wide",  max_height: 900.0 },
  { max_eased: nil,   css_class: "grid-stack", max_height: 1200.0 }
].freeze

# Width of the widest row. Nothing is drawn wider: a figure that runs off the
# side has to be scrolled to be read whole, and the gallery already has a
# better answer for that — clicking opens it at full size.
CONTAINER_WIDTH = 940.0

EXPONENT = 0.75
# Chosen so that a 280px-wide figure is shown at ~90% of its rendered size.
COEFFICIENT = 3.68

# Width and height out of the PNG's IHDR chunk, which always starts at byte 16.
def png_size(path)
  header = File.binread(path, 24)
  raise "#{path}: not a PNG" unless header && header[1, 3] == "PNG"

  header[16, 8].unpack("N2")
end

def eased_width(width)
  COEFFICIENT * (width**EXPONENT)
end

def layout_for(eased)
  LAYOUTS.find { |l| l[:max_eased].nil? || eased <= l[:max_eased] }
end

def display_scale(width, height, eased, max_height)
  [eased / width, max_height / height, 1.0].min
end

sizes = Dir.glob(File.join(IMG_DIR, "*.png")).sort.each_with_object({}) do |path, acc|
  name = File.basename(path, ".png")
  width, height = png_size(path)
  eased = eased_width(width)
  layout = layout_for(eased)
  scale = [display_scale(width, height, eased, layout[:max_height]), CONTAINER_WIDTH / width].min
  acc[name] = {
    "width" => (width * scale).round,
    "height" => (height * scale).round,
    "layout" => layout[:css_class]
  }
end

abort "no figures found in #{IMG_DIR}" if sizes.empty?

FileUtils.mkdir_p(File.dirname(DATA_FILE))
File.write(DATA_FILE, <<~HEADER + sizes.to_yaml.sub(/\A---\n/, ""))
  # Generated by dev/stamp_figure_sizes.rb — do not edit by hand.
  # Display size of each gallery figure, eased down by a factor that grows with
  # the figure's width so the apparent scale stays comparable from one figure to
  # the next, plus the grid class that decides how much of the row it gets.
HEADER

puts "wrote #{sizes.size} figure sizes to #{DATA_FILE.sub("#{Dir.pwd}/", "")}"

# The manual's figures, by the same reckoning. Every one is drawn at the same
# font size, so left to fit their column each on its own a narrow figure would
# be shown whole and a wide one halved, and the same 16px lettering would look
# twice the size in one figure as in the next.
def svg_size(path)
  head = File.read(path, 400)
  [head[/\bwidth="([\d.]+)/, 1].to_f, head[/\bheight="([\d.]+)/, 1].to_f]
end

if Dir.exist?(DOC_DIR)
  doc_sizes = Dir.glob(File.join(DOC_DIR, "*.svg")).sort.each_with_object({}) do |path, acc|
    width, height = svg_size(path)
    next if width.zero? || height.zero?

    eased = eased_width(width)
    tier = DOC_LAYOUTS.find { |l| l[:max_width].nil? || eased <= l[:max_width] }
    scale = [eased / width, 900.0 / height, 1.0, tier[:column] / width].min
    acc[File.basename(path, ".svg")] = {
      "width" => (width * scale).round,
      "height" => (height * scale).round,
      "layout" => tier[:css_class]
    }
  end

  File.write(DOC_DATA_FILE, <<~HEADER + doc_sizes.to_yaml.sub(/\A---\n/, ""))
    # Generated by dev/stamp_figure_sizes.rb — do not edit by hand.
    # Display size of each figure beside an example in the manual, eased the same
    # way the gallery's are so that the lettering keeps one apparent size across
    # figures of different widths.
  HEADER
  puts "wrote #{doc_sizes.size} doc figure sizes to #{DOC_DATA_FILE.sub("#{Dir.pwd}/", "")}"
end
