# frozen_string_literal: true

# Records the display size of every gallery figure in docs/_data/figure_sizes.yml.
#
# The gallery used to hand each PNG to the browser with no size, so a figure was
# drawn at its natural size when it fitted the column and shrunk when it did
# not. Since a tree's pixel size follows its content, a short tree appeared at
# 100% next to a wide one at 30%, and the same 16px label looked twice as large
# in one figure as in the next.
#
# A single scale factor for every figure is no better: it either leaves the
# small figures too large or shrinks them past the point of being readable,
# while the wide ones are governed by the column regardless. So the factor
# varies with the figure's own width, easing from full size for a tiny tree
# down to the column limit for a wide one:
#
#   displayed width = min(column, k * width ** EXPONENT)
#
# An exponent below 1 makes the displayed width grow more slowly than the
# figure itself, which is exactly the compression the eye is asking for; k is
# set so that a 280px figure lands at about 90%. The result runs roughly 100%
# for a tiny tree, 90% at 280px, 77% at 520px, 65% at 690px, and meets the
# column cap from there on — a gradient rather than the step a fixed factor
# produces. Nothing is ever scaled up.
#
# Jekyll cannot measure images on GitHub Pages, hence this file. Run from the
# repository root, after generating the examples:
#
#   ruby dev/stamp_figure_sizes.rb

require "yaml"
require "fileutils"

IMG_DIR = File.expand_path("../docs/assets/img", __dir__)
DATA_FILE = File.expand_path("../docs/_data/figure_sizes.yml", __dir__)

# Usable width of the figure column, measured on the built page. Mirrors the
# grid in docs/assets/css/style.scss; the stylesheet still caps anything wider,
# so an approximation here costs nothing.
COLUMN_WIDTH = 448.0
EXPONENT = 0.75
# Chosen so that a 280px-wide figure is shown at ~90% of its rendered size.
COEFFICIENT = 3.68

# Width and height out of the PNG's IHDR chunk, which always starts at byte 16.
def png_size(path)
  header = File.binread(path, 24)
  raise "#{path}: not a PNG" unless header && header[1, 3] == "PNG"

  header[16, 8].unpack("N2")
end

def display_scale(width)
  eased = COEFFICIENT * (width**EXPONENT)
  [[eased, COLUMN_WIDTH].min / width, 1.0].min
end

sizes = Dir.glob(File.join(IMG_DIR, "*.png")).sort.each_with_object({}) do |path, acc|
  name = File.basename(path, ".png")
  width, height = png_size(path)
  scale = display_scale(width)
  acc[name] = {
    "width" => (width * scale).round,
    "height" => (height * scale).round
  }
end

abort "no figures found in #{IMG_DIR}" if sizes.empty?

FileUtils.mkdir_p(File.dirname(DATA_FILE))
File.write(DATA_FILE, <<~HEADER + sizes.to_yaml.sub(/\A---\n/, ""))
  # Generated by dev/stamp_figure_sizes.rb — do not edit by hand.
  # Display size of each gallery figure: its rendered size eased down by a
  # factor that grows with the figure's width, so the apparent scale stays
  # comparable from one figure to the next.
HEADER

puts "wrote #{sizes.size} figure sizes to #{DATA_FILE.sub("#{Dir.pwd}/", "")}"
